"""
Replicates Example 3.3 / Figure 3.4: Langevin dynamics sampling from a known
Gaussian mixture score function.

    p(x) = pi_1 N(x | mu_1, sigma_1^2) + pi_2 N(x | mu_2, sigma_2^2)

Langevin update (score-based sampling, using the true score grad_x log p(x)
since p is known in closed form here — no learned score network needed):

    x_{t+1} = x_t + (eta / 2) * grad_x log p(x_t) + sqrt(eta) * z_t,   z_t ~ N(0, 1)

M samples are initialized uniformly on [-3, 3] and evolve under the update
above; as t grows their histogram converges to p(x), even though it started
from a completely different (uniform) distribution.
"""

import numpy as np
import matplotlib.pyplot as plt

# --- mixture settings (matching the example) ---
PI = (0.6, 0.4)
MU = (2.0, -2.0)
SIGMA = (0.5, 0.2)

M = 10000          # number of samples / particles
ETA = 0.05         # Langevin step size
T_STEPS = [0, 1, 10, 100]
X_RANGE = (-5, 5)

rng = np.random.default_rng(0)


def pdf(x):
    return sum(p * np.exp(-0.5 * ((x - mu) / s) ** 2) / (s * np.sqrt(2 * np.pi))
               for p, mu, s in zip(PI, MU, SIGMA))


def score(x):
    """grad_x log p(x) for the mixture, via responsibility-weighted component scores."""
    comp_pdfs = [p * np.exp(-0.5 * ((x - mu) / s) ** 2) / (s * np.sqrt(2 * np.pi))
                 for p, mu, s in zip(PI, MU, SIGMA)]
    total = sum(comp_pdfs)
    comp_scores = [-(x - mu) / (s ** 2) for mu, s in zip(MU, SIGMA)]
    weighted = sum(w * cs for w, cs in zip(comp_pdfs, comp_scores))
    return weighted / total


def run():
    x = rng.uniform(-3, 3, size=M)
    xs = np.linspace(*X_RANGE, 500)
    true_pdf = pdf(xs)

    snapshots = {}
    t = 0
    max_t = max(T_STEPS)
    if t in T_STEPS:
        snapshots[t] = x.copy()

    while t < max_t:
        z = rng.normal(size=M)
        x = x + (ETA / 2) * score(x) + np.sqrt(ETA) * z
        t += 1
        if t in T_STEPS:
            snapshots[t] = x.copy()

    fig, axes = plt.subplots(1, len(T_STEPS), figsize=(4 * len(T_STEPS), 3.5))
    for ax, t in zip(axes, T_STEPS):
        ax.hist(snapshots[t], bins=100, range=X_RANGE, density=True, color="gold", edgecolor="gold")
        ax.plot(xs, true_pdf, color="red", linewidth=1.5)
        ax.set_title(f"t = {t}")
        ax.set_xlim(*X_RANGE)

    fig.suptitle("Samples generated by Langevin dynamics")
    fig.tight_layout()

    out_path = "langevin_samples.pdf"
    fig.savefig(out_path, dpi=400)
    print(f"Saved figure to {out_path}")


if __name__ == "__main__":
    run()
